version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/apigatewayplayground
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: "docker build -t $DOCKER_USER/apigatewayplayground_customers:$CIRCLE_BRANCH ."
      - run: "docker push $DOCKER_USER/apigatewayplayground_customers:$CIRCLE_BRANCH"

