apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: gateway
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: xvincentx/apigatewayplayground_gateway:microservice-gateway-hypermedia
